RoomReservation/RoomReservation/Controllers/ReservationController.cs
using RoomReservation.DB.Models;
using RoomReservation.Helpers;
using RoomReservation.Models;
using RoomReservation.Repositories;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Web;
using System.Web.Mvc;

namespace RoomReservation.Controllers
{

    public class ReservationController : Controller
    {
        protected long UserId
        {
            get
            {
                return long.Parse(((ClaimsIdentity)User.Identity).Claims.FirstOrDefault(x => x.Type == "UserId").Value);
            }
        }
        // GET: Reservation
        public ActionResult Index()
        {
            return View();
        }

        [HttpGet]
        [Authorize]
        public ActionResult ReservationList()
        {
            try
            {
                return View(new ReservationListViewModel());
            }
            catch (Exception ex)
            {
                LogHelper.Log.Error(ex);
                return View("Error");
            }
        }
        [HttpGet]
        [Authorize]
        public ActionResult ReservationDetails(long? id)
        {
            try
            {
                EditReservationViewModel model = new EditReservationViewModel();
                ReservationRepository reservationRepository = new ReservationRepository();
                if (id.HasValue == true)
                {
                    RRReservation pobranaRezerwacja = reservationRepository.GetById(id.Value);
                    model.Id = pobranaRezerwacja.Id;
                    model.Date = pobranaRezerwacja.Date;
                    model.RRRoomId = pobranaRezerwacja.RRRoomId;
                }
                return View("ReservationDetails", model);
            }
            catch (Exception ex)
            {
                LogHelper.Log.Error(ex);
                return View("Error");
            }
        }



        [HttpPost]
        [Authorize]
        public ActionResult SaveReservationDetails(EditReservationViewModel model)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    ReservationRepository reservationRepository = new ReservationRepository();
                    RRReservation reservation = null;
                    if (model.Id.HasValue)
                    {
                        reservation = reservationRepository.GetById(model.Id.Value);
                    }
                    else
                    {
                        reservation = new RRReservation();
                        reservation.Status = RoomReservation.Enum.ReservationStatus.InProgress;
                    }
                    reservation.Date = model.Date.Value;
                    reservation.RRRoomId = model.RRRoomId.Value;
                    reservation.RRUserId = UserId;
                    long? rezultatZapisu = reservationRepository.Save(reservation);
                    if (rezultatZapisu == null)
                    {
                        return View("Error");
                    }
                    else
                    {
                        return RedirectToAction("ReservationList");
                    }
                }
                else
                {
                    return View("Error");
                }
            }
            catch (Exception ex)
            {
                LogHelper.Log.Error(ex);
                return View("Error");
            }
        }


        [Authorize]
        [HttpPost]
        public ActionResult DeleteReservation(long id)
        {
            try
            {
                if (ModelState.IsValid == true)
                {
                    ReservationRepository reservationRepository = new ReservationRepository();
                    bool deleteResult = reservationRepository.Delete(id);
                    return RedirectToAction("ReservationList");
                }
                else
                {
                    return View("Error");
                }
            }
            catch (Exception ex)
            {
                LogHelper.Log.Error(ex);
                return View("Error");
            }
        }
    }
}

RoomReservation/RoomReservation/Controllers/RoomController.cs
using RoomReservation.DB.Models;
using RoomReservation.Helpers;
using RoomReservation.Models;
using RoomReservation.Repositories;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace RoomReservation.Controllers
{
    [Authorize(Roles = "Admin")]
    public class RoomController : Controller
    {
        [HttpGet]
        public ActionResult RoomList()
        {
            try
            {
                return View("RoomList");
            }
            catch (Exception ex)
            {
                LogHelper.Log.Error(ex);
                return View("Error");
            }
        }
    }
}

RoomReservation/RoomReservation/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/js")

    <script>
        $(document).ready(function () {
            $('.input-group.date-time').datetimepicker({
                locale: 'pl'
            });



            $('.input-group.date').datetimepicker({
                locale: 'pl',
                format: 'YYYY-MM-DD'
            });
            $('.input-group.date').on("dp.change", function (e) {
                $(this).find('input').val(e.date.format('YYYY-MM-DD')).trigger('change');
            });
        });
    </script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Strona główna", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                @if (User.Identity.IsAuthenticated)
                {
                    <ul class="nav navbar-nav">
                        @if (User.IsInRole("Admin"))
                        {
                            <li>@Html.ActionLink("Pomieszczenia", "RoomList", "Room")</li>
                        }
                        <li>@Html.ActionLink("Rezerwacje", "ReservationList", "Reservation")</li>
                    </ul>
                }
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Rezerwacja pomieszczeń</p>
        </footer>
    </div>

    @RenderSection("scripts", required: false)
</body>
</html>